//ocv action types
export const CLICK_LOGIN_ACTION = 'CLICK_LOGIN_ACTION';
export const CLICK_LOGOUT_ACTION = 'CLICK_LOGOUT_ACTION';
export const CLICK_SIGNUP_ACTION = 'CLICK_SIGNUP_ACTION';

export const LOAD_OCVS_ACTION = 'LOAD_OCVS_ACTION';
export const LOAD_OCVS_ACTION_SUCCESS = 'LOAD_OCVS_ACTION_SUCCESS';
export const LOAD_OCVS_ACTION_FAIL = 'LOAD_OCVS_ACTION_FAIL';

export const LOAD_OCV_REASONS_ACTION = 'LOAD_OCV_REASONS_ACTION';
export const LOAD_OCV_REASONS_ACTION_SUCCESS = 'LOAD_OCV_REASONS_ACTION_SUCCESS';
export const LOAD_OCV_REASONS_ACTION_FAIL = 'LOAD_OCV_REASONS_ACTION_FAIL';

export const LOAD_CLARITY_RULES_ACTION = 'LOAD_CLARITY_RULES_ACTION';
export const LOAD_CLARITY_RULES_ACTION_SUCCESS = 'LOAD_CLARITY_RULES_ACTION_SUCCESS';
export const LOAD_CLARITY_RULES_ACTION_FAIL = 'LOAD_CLARITY_RULES_ACTION_FAIL';

export const LOAD_PROJECTS_ACTION = 'LOAD_PROJECTS_ACTION';
export const LOAD_PROJECTS_ACTION_SUCCESS = 'LOAD_PROJECTS_ACTION_SUCCESS';
export const LOAD_PROJECTS_ACTION_FAIL = 'LOAD_PROJECTS_ACTION_FAIL';

export const SAVE_OCV_ACTION = 'SAVE_OCV_ACTION';
export const SAVE_OCV_ACTION_SUCCESS = 'SAVE_OCV_ACTION_SUCCESS';
export const SAVE_OCV_ACTION_FAIL = 'SAVE_OCV_ACTION_FAIL';

export const DELETE_OCV_ACTION = 'DELETE_OCV_ACTION';
export const DELETE_OCV_ACTION_SUCCESS = 'DELETE_OCV_ACTION_SUCCESS';
export const DELETE_OCV_ACTION_FAIL = 'DELETE_OCV_ACTION_FAIL';

export const UPLOAD_FILE_ACTION = 'UPLOAD_FILE_ACTION';
export const UPLOAD_FILE_ACTION_SUCCESS = 'UPLOAD_FILE_ACTION_SUCCESS';
export const UPLOAD_FILE_ACTION_FAIL = 'UPLOAD_FILE_ACTION_FAIL';

//codeReview action types
export const LOAD_REVIEW_REQUESTS_ACTION = 'LOAD_REVIEW_REQUESTS_ACTION';
export const LOAD_REVIEW_REQUESTS_ACTION_SUCCESS = 'LOAD_REVIEW_REQUESTS_ACTION_SUCCESS';
export const LOAD_REVIEW_REQUESTS_ACTION_FAIL = 'LOAD_REVIEW_REQUESTS_ACTION_FAIL';

export const LOAD_REVIEW_REQUEST_REASONS_ACTION = 'LOAD_REVIEW_REQUEST_REASONS_ACTION';
export const LOAD_REVIEW_REQUEST_REASONS_ACTION_SUCCESS = 'LOAD_REVIEW_REQUEST_REASONS_ACTION_SUCCESS';
export const LOAD_REVIEW_REQUEST_REASONS_ACTION_FAIL = 'LOAD_REVIEW_REQUEST_REASONS_ACTION_FAIL';

export const SAVE_REVIEW_REQUEST_ACTION = 'SAVE_REVIEW_REQUEST_ACTION';
export const SAVE_REVIEW_REQUEST_ACTION_SUCCESS = 'SAVE_REVIEW_REQUEST_ACTION_SUCCESS';
export const SAVE_REVIEW_REQUEST_ACTION_FAIL = 'SAVE_REVIEW_REQUEST_ACTION_FAIL';

export const DELETE_REVIEW_REQUEST_ACTION = 'DELETE_REVIEW_REQUEST_ACTION';
export const DELETE_REVIEW_REQUEST_ACTION_SUCCESS = 'DELETE_REVIEW_REQUEST_ACTION_SUCCESS';
export const DELETE_REVIEW_REQUEST_ACTION_FAIL = 'DELETE_REVIEW_REQUEST_ACTION_FAIL';

export const LOAD_INCOMING_REVIEW_REQUESTS_ACTION = 'LOAD_INCOMING_REVIEW_REQUESTS_ACTION';
export const LOAD_INCOMING_REVIEW_REQUESTS_ACTION_SUCCESS = 'LOAD_INCOMING_REVIEW_REQUESTS_ACTION_SUCCESS';
export const LOAD_INCOMING_REVIEW_REQUESTS_ACTION_FAIL = 'LOAD_INCOMING_REVIEW_REQUESTS_ACTION_FAIL';

export const LOAD_REVIEW_CLASSES_ACTION = 'LOAD_REVIEW_CLASSES_ACTION';
export const LOAD_REVIEW_CLASSES_ACTION_SUCCESS = 'LOAD_REVIEW_CLASSES_ACTION_SUCCESS';
export const LOAD_REVIEW_CLASSES_ACTION_FAIL = 'LOAD_REVIEW_CLASSES_ACTION_FAIL';

export const SAVE_REVIEW_CLASSES_ACTION = 'SAVE_REVIEW_CLASSES_ACTION';
export const SAVE_REVIEW_CLASSES_ACTION_SUCCESS = 'SAVE_REVIEW_CLASSES_ACTION_SUCCESS';
export const SAVE_REVIEW_CLASSES_ACTION_FAIL = 'SAVE_REVIEW_CLASSES_ACTION_FAIL';

export const LOAD_REVIEWS_COMPLETED_ACTION = 'LOAD_REVIEWS_COMPLETED_ACTION';
export const LOAD_REVIEWS_COMPLETED_ACTION_SUCCESS = 'LOAD_REVIEWS_COMPLETED_ACTION_SUCCESS';
export const LOAD_REVIEWS_COMPLETED_ACTION_FAIL = 'LOAD_REVIEWS_COMPLETED_ACTION_FAIL';

//utils action types
export const SAVE_AUDIT_ACTION = 'SAVE_AUDIT_ACTION';
export const SAVE_AUDIT_ACTION_SUCCESS = 'SAVE_AUDIT_ACTION_SUCCESS';
export const SAVE_AUDIT_ACTION_FAIL = 'SAVE_AUDIT_ACTION_FAIL';

export const LOAD_USERS_ACTION = 'LOAD_USERS_ACTION';
export const LOAD_USERS_ACTION_SUCCESS = 'LOAD_USERS_ACTION_SUCCESS';
export const LOAD_USERS_ACTION_FAIL = 'LOAD_USERS_ACTION_FAIL';

