alva.Constants = {
	APPLICATION_DATA_USER: "APPLICATION_DATA_USER",
	APPLICATION_DATA_USER_SETTINGS: "APPLICATION_DATA_USER_SETTINGS",

	PAGE_CONTENT: "content",

	PAGE_DIAGRAM: "diagram",
	

	ALERT_TYPE_ERROR: "alert-danger",
	ALERT_TYPE_SUCCESS: "alert-success",
	ALERT_TYPE_INFO: "alert-info",
	ALERT_TYPE_WARNING: "alert-warning",


	EVENT_PAGE_LOADED: "EVENT_PAGE_LOADED",
	EVENT_PAGE_CONTENT_LOADED: "EVENT_PAGE_CONTENT_LOADED",
	EVENT_LEFT_BAR_LOADED: "EVENT_LEFT_BAR_LOADED",
	EVENT_RIGHT_BAR_LOADED: "EVENT_RIGHT_BAR_LOADED",
	EVENT_MENU_TOGGLE_CLICKED: "EVENT_MENU_TOGGLE_CLICKED",

	SESSION_PARAMETER_LANGUAGE: 'SESSION_PARAMETER_LANGUAGE',

}