export const Constants = Object.freeze({
    ROLE_ADMIN: '00000001',
    ROLE_TEAM_LEAD: '00000010',
    ROLE_DEVELOPER: '00000100',
    ROLE_REVIEWER: '00001000',

    //START AUDIT    
    AUDIT_SIGN_UP: 'AUDIT_SIGN_UP',

    AUDIT_ENTER_OCV_PAGE: 'AUDIT_ENTER_OCV_PAGE',
    AUDIT_OCV_ADD: 'AUDIT_OCV_ADD',
    AUDIT_OCV_OPEN_EDIT_FORM: 'AUDIT_OCV_OPEN_EDIT_FORM',
    AUDIT_OCV_EDIT: 'AUDIT_OCV_EDIT',
    AUDIT_OCV_DELETE: 'AUDIT_OCV_DELETE',
    AUDIT_OCV_CLOSE: 'AUDIT_OCV_CLOSE',
    AUDIT_OCV_REOPEN: 'AUDIT_OCV_REOPEN',

    AUDIT_ENTER_OCV_REPORTS_PAGE: 'AUDIT_ENTER_OCV_REPORTS_PAGE',

    AUDIT_ENTER_REVIEW_REPORTS_PAGE: 'AUDIT_ENTER_REVIEW_REPORTS_PAGE',

    AUDIT_ENTER_METRICS_REPORTS_PAGE: 'AUDIT_ENTER_METRICS_REPORTS_PAGE',

    AUDIT_ENTER_ADMIN_PAGE: 'AUDIT_ENTER_ADMIN_PAGE',
    
    AUDIT_ENTER_CODE_REVIEW_PAGE: 'AUDIT_ENTER_CODE_REVIEW_PAGE',
    AUDIT_CODE_REVIEW_OPEN_REVIEW_REQUEST_EDIT_FORM: 'AUDIT_CODE_REVIEW_OPEN_REVIEW_REQUEST_EDIT_FORM',
    AUDIT_CODE_REVIEW_OPEN_REVIEW_REQUEST_REVIEW_FORM: 'AUDIT_CODE_REVIEW_OPEN_REVIEW_REQUEST_REVIEW_FORM',
    AUDIT_CODE_REVIEW_ADD_REVIEW_REQUEST: 'AUDIT_CODE_REVIEW_ADD_REVIEW_REQUEST',
    AUDIT_CODE_REVIEW_EDIT_REVIEW_REQUEST: 'AUDIT_CODE_REVIEW_EDIT_REVIEW_REQUEST',
    AUDIT_CODE_REVIEW_REQUEST_REVIEWING_SAVE: 'AUDIT_CODE_REVIEW_REQUEST_REVIEWING_SAVE',
    AUDIT_CODE_REVIEW_REQUEST_REVIEWING_DONE: 'AUDIT_CODE_REVIEW_REQUEST_REVIEWING_DONE',
    AUDIT_CODE_REVIEW_DELETE: 'AUDIT_CODE_REVIEW_DELETE',
    AUDIT_CODE_REVIEW_OPEN_INCOMING_REVIEW_REQUEST_FORM: 'AUDIT_CODE_REVIEW_OPEN_INCOMING_REVIEW_REQUEST_FORM',
    AUDIT_CODE_REVIEW_CLASS_SAVE: 'AUDIT_CODE_REVIEW_CLASS_SAVE',
    //END AUDIT
})